language: go

go:
    - 1.5.1
    - tip

before_install:
    - go get github.com/stretchr/testify/assert
    - go get github.com/onsi/gomega
    - go get github.com/onsi/ginkgo
    - go get golang.org/x/tools/cmd/cover

script: 
    - make lint
    - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)